name: Debug Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSH Deploy Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart ssh
            cd ${{ secrets.PROJECT_PATH }}
            git reset --hard HEAD
            git clean -fd
            git pull origin master --prune --force || true
